name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  BIN_NAME: tui # CHANGE THIS

jobs:
  windows:
    name: Windows x64
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Package
        shell: pwsh
        run: |
          mkdir dist

          Copy-Item `
            target\release\${env:BIN_NAME}.exe `
            dist\

          Compress-Archive `
            -Path dist\* `
            -DestinationPath `
            ${env:BIN_NAME}-windows-x64.zip

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.zip

  linux:
    name: Linux x64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            pkg-config \
            libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Package
        run: |
          mkdir dist

          cp target/release/${BIN_NAME} dist/

          tar -czf \
            ${BIN_NAME}-linux-x64.tar.gz \
            -C dist .

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz

  macos:
    name: macOS Universal
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: |
            x86_64-apple-darwin
            aarch64-apple-darwin

      - name: Build Intel
        run: |
          cargo build \
            --release \
            --target x86_64-apple-darwin

      - name: Build Apple Silicon
        run: |
          cargo build \
            --release \
            --target aarch64-apple-darwin

      - name: Create Universal Binary
        run: |
          mkdir universal

          lipo -create \
            target/x86_64-apple-darwin/release/${BIN_NAME} \
            target/aarch64-apple-darwin/release/${BIN_NAME} \
            -output universal/${BIN_NAME}

      - name: Package
        run: |
          tar -czf \
            ${BIN_NAME}-macos-universal.tar.gz \
            -C universal .

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
